#!/bin/bash
# https://raspberrypi.stackexchange.com/questions/100195
interfaceWifi=wlan0
interfaceWired=eth0

### Check if run as root ############################
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 
	echo "Try \"sudo $0 $*\""	
	exit 1
fi

### FUNCTIONS ##########################################

wpa_cli -i$interfaceWifi select_network 0
systemctl restart systemd-networkd
sleep 1

# Check if ethernet cable is plugged in. If so create hotspot and exit
if [ "$(cat /sys/class/net/${interfaceWired}/carrier)" = "1" ]; then
	echo "There is a wired connection. Enable hotspot"
	if wpa_cli -i$interfaceWifi status | grep -q "mode=station"; then
		wpa_cli -i$interfaceWifi select_network 0
		configure_ap
	fi	
	exit 0
fi

exit 0